### Get Raw JSON Data
Bash Script

In [ ]:
#/bin/bash
%%bash
# Base API URLs
API_BASE_URL_MAKES="https://api.nhtsa.gov/products/vehicle/makes?modelYear="
API_BASE_URL_MODELS="https://api.nhtsa.gov/products/vehicle/models?"
API_BASE_URL_RECALLS="https://api.nhtsa.gov/recalls/recallsByVehicle?make=%s&model=%s&modelYear=%s"

# Get current year
CURRENT_YEAR=$(date +%Y)

# Calculate start year (last 5 years including current)
START_YEAR=$((CURRENT_YEAR - 9))

# Remove any existing JSON files to start fresh for this comprehensive run
rm -f year_*.json

echo "Starting comprehensive data fetch for model years from $START_YEAR to $CURRENT_YEAR..."

# Loop through the defined years
for (( YEAR=$START_YEAR; YEAR<=$CURRENT_YEAR; YEAR++ ))
do
    echo "\n--- Processing year: $YEAR ---"

    # 1. Fetch Makes for the current year
    API_URL_MAKE="${API_BASE_URL_MAKES}${YEAR}&issueType=r"
    RESPONSE_MAKE=$(curl -s "$API_URL_MAKE")

    MAKE_FILE="year_${YEAR}_makes.json"
    echo "$RESPONSE_MAKE" > "$MAKE_FILE"
    echo "Saved raw makes response for year $YEAR to $MAKE_FILE"

    # Check if the makes file exists and is not empty before processing
    if [ -s "$MAKE_FILE" ]; then
        # Extract unique makes using jq
        UNIQUE_MAKES=$(jq -r '.results[].make' "$MAKE_FILE" | sort -u)

        # Use IFS to correctly iterate over make names with spaces
        OLD_IFS=$IFS
        IFS=$'\n'
        for MAKE in $UNIQUE_MAKES
        do
            # URL-encode the make name
            ENCODED_MAKE_NAME=$(python3 -c 'import urllib.parse, sys; print(urllib.parse.quote_plus(sys.argv[1]))' "$MAKE")

            # 2. Fetch Models for the current year and make
            API_URL_MODEL="${API_BASE_URL_MODELS}modelYear=${YEAR}&make=${ENCODED_MAKE_NAME}&issueType=r"
            RESPONSE_MODEL=$(curl -s "$API_URL_MODEL")

            # Extract the 'Count' for models, default to 0 if null
            MODEL_COUNT=$(echo "$RESPONSE_MODEL" | jq '.count // 0')

            if [ "$MODEL_COUNT" -gt 0 ]; then
                SAFE_MAKE_NAME=$(echo "$MAKE" | tr ' ' '_')
                MODEL_FILE="year_${YEAR}_make_${SAFE_MAKE_NAME}_models.json"
                echo "$RESPONSE_MODEL" > "$MODEL_FILE"
                echo "  Saved models for year $YEAR, make '$MAKE' (Count: $MODEL_COUNT) to $MODEL_FILE"

                # Extract unique models from the current model file
                MODELS=$(jq -r '.results[].model' "$MODEL_FILE" | sort -u)

                if [ -z "$MODELS" ]; then
                    echo "  No distinct models found in $MODEL_FILE. Skipping recall fetching for this make.\n"
                    continue
                fi

                for MODEL in $MODELS
                do
                    # URL-encode the model name
                    ENCODED_MODEL_NAME=$(python3 -c 'import urllib.parse, sys; print(urllib.parse.quote_plus(sys.argv[1]))' "$MODEL")

                    # 3. Fetch Recalls for the current year, make, and model
                    API_URL_RECALL_SPECIFIC=$(printf "$API_BASE_URL_RECALLS" "$ENCODED_MAKE_NAME" "$ENCODED_MODEL_NAME" "$YEAR")
                    RESPONSE_RECALL=$(curl -s "$API_URL_RECALL_SPECIFIC")

                    # Extract the 'Count' for recalls, default to 0 if null
                    RECALL_COUNT=$(echo "$RESPONSE_RECALL" | jq '.Count // 0')

                    if [ "$RECALL_COUNT" -gt 0 ]; then
                        SAFE_MODEL_NAME=$(echo "$MODEL" | tr ' ' '_')
                        RECALL_FILE="year_${YEAR}_make_${SAFE_MAKE_NAME}_model_${SAFE_MODEL_NAME}_recalls.json"
                        echo "$RESPONSE_RECALL" > "$RECALL_FILE"
                        echo "    Saved recalls for year $YEAR, make '$MAKE', model '$MODEL' (Count: $RECALL_COUNT) to $RECALL_FILE"
                    else
                        echo "    No recalls found for year $YEAR, make '$MAKE', model '$MODEL' (Count: $RECALL_COUNT). Skipping file save."
                    fi
                done
            else
                echo "  No models found for year $YEAR, make '$MAKE' (Count: $MODEL_COUNT). Skipping model and recall fetch.\n"
            fi
        done
        IFS=$OLD_IFS # Restore original IFS
    else
        echo "Warning: $MAKE_FILE is empty or does not exist. Skipping model and recall fetching for this year.\n"
    fi
done

### Put Raw Data Into Folders

In [ ]:
#/bin/bash
%%bash
# Get current year and start year from previous
CURRENT_YEAR=$(date +%Y)
START_YEAR=$((CURRENT_YEAR - 9))

echo "Organizing files for model years from $START_YEAR to $CURRENT_YEAR..."

# Loop through the defined years to create directories and move files
for (( YEAR=$START_YEAR; YEAR<=$CURRENT_YEAR; YEAR++ ))
do
    echo "\n--- Organizing data for year: $YEAR ---"

    # Create year-specific directories if they don't exist
    mkdir -p "data/${YEAR}/makes"
    mkdir -p "data/${YEAR}/models"
    mkdir -p "data/${YEAR}/recalls"

    # Move makes files
    if [ -f "year_${YEAR}_makes.json" ]; then
        mv "year_${YEAR}_makes.json" "data/${YEAR}/makes/"
        echo "Moved year_${YEAR}_makes.json to data/${YEAR}/makes/"
    fi

    # Move models files
    # The models files are named year_YYYY_make_MAKE_models.json
    for model_file in year_${YEAR}_make_*_models.json; do
        if [ -f "$model_file" ]; then
            mv "$model_file" "data/${YEAR}/models/"
            echo "Moved $model_file to data/${YEAR}/models/"
        fi
    done

    # Move recalls files
    # The recalls files are named year_YYYY_make_MAKE_model_MODEL_recalls.json
    for recall_file in year_${YEAR}_make_*_model_*_recalls.json; do
        if [ -f "$recall_file" ]; then
            mv "$recall_file" "data/${YEAR}/recalls/"
            echo "Moved $recall_file to data/${YEAR}/recalls/"
        fi
    done
done

Organizing files for model years from 2016 to 2025...
\n--- Organizing data for year: 2016 ---
Moved year_2016_makes.json to data/2016/makes/
Moved year_2016_make_ACURA_models.json to data/2016/models/
Moved year_2016_make_AIRSTREAM_models.json to data/2016/models/
Moved year_2016_make_AMERICAN_COACH_models.json to data/2016/models/
Moved year_2016_make_APRILIA_models.json to data/2016/models/
Moved year_2016_make_ASTON_MARTIN_models.json to data/2016/models/
Moved year_2016_make_AUDI_models.json to data/2016/models/
Moved year_2016_make_AVION_models.json to data/2016/models/
Moved year_2016_make_BIG_TEX_models.json to data/2016/models/
Moved year_2016_make_BISON_models.json to data/2016/models/
Moved year_2016_make_BLUE_BIRD_models.json to data/2016/models/
Moved year_2016_make_BMW_models.json to data/2016/models/
Moved year_2016_make_BRAUNABILITY_models.json to data/2016/models/
Moved year_2016_make_BUICK_models.json to data/2016/models/
Moved year_2016_make_CADILLAC_models.json to data/2016/models/
Moved year_2016_make_CAN-AM_models.json to data/2016/models/
Moved year_2016_make_CARGO_EXPRESS_models.json to data/2016/models/
Moved year_2016_make_CARGO_MATE_models.json to data/2016/models/
Moved year_2016_make_CEDAR_CREEK_models.json to data/2016/models/
Moved year_2016_make_CHARMAC_models.json to data/2016/models/
Moved year_2016_make_CHEROKEE_models.json to data/2016/models/
Moved year_2016_make_CHEVROLET_models.json to data/2016/models/
Moved year_2016_make_CHRYSLER_models.json to data/2016/models/
Moved year_2016_make_C&M_models.json to data/2016/models/
Moved year_2016_make_COACHMEN_models.json to data/2016/models/
Moved year_2016_make_CROSSROADS_models.json to data/2016/models/
Moved year_2016_make_CRUISER_RV_models.json to data/2016/models/
Moved year_2016_make_DODGE_models.json to data/2016/models/
Moved year_2016_make_DRV_models.json to data/2016/models/
Moved year_2016_make_DUCATI_models.json to data/2016/models/
Moved year_2016_make_DUTCHMEN_models.json to data/2016/models/
Moved year_2016_make_DYNAMAX_models.json to data/2016/models/
Moved year_2016_make_EAST_MANUFACTURING_models.json to data/2016/models/
Moved year_2016_make_ENTEGRA_models.json to data/2016/models/
Moved year_2016_make_EVERGREEN_models.json to data/2016/models/
Moved year_2016_make_ACURA_model_ILX_recalls.json to data/2016/recalls/
Moved year_2016_make_ACURA_model_MDX_recalls.json to data/2016/recalls/
Moved year_2016_make_ACURA_model_RDX_recalls.json to data/2016/recalls/
Moved year_2016_make_ACURA_model_TLX_recalls.json to data/2016/recalls/
Moved year_2016_make_AIRSTREAM_model_INTERSTATE_recalls.json to data/2016/recalls/
Moved year_2016_make_AIRSTREAM_model_SPORT_recalls.json to data/2016/recalls/
Moved year_2016_make_AMERICAN_COACH_model_AMERICAN_ALLEGIANCE_recalls.json to data/2016/recalls/
Moved year_2016_make_AMERICAN_COACH_model_AMERICAN_EAGLE_recalls.json to data/2016/recalls/
Moved year_2016_make_APRILIA_model_CAPONORD_RALLY_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_A3_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_A3_SPORTBACK_E-TRON_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_A5_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_A6_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_A7_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_Q3_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_Q5_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_Q7_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_RS7_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_S3_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_S6_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_S7_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_S8_recalls.json to data/2016/recalls/
Moved year_2016_make_AUDI_model_TT_recalls.json to data/2016/recalls/
Moved year_2016_make_AVION_model_AZURE_recalls.json to data/2016/recalls/
Moved year_2016_make_BISON_model_SILVERADO_recalls.json to data/2016/recalls/
Moved year_2016_make_BLUE_BIRD_model_ALL_AMERICAN_recalls.json to data/2016/recalls/
Moved year_2016_make_BLUE_BIRD_model_VISION_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_740LI_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_750LI_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_750LXI_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_C600_SPORT_MAXI-SCOOTER_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_C650_GT_MAXI-SCOOTER_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_G650GS_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_I3_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_M2_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_M3_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_M4_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_M5_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_M6_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_R1200_GS_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_R1200_RS_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_S1000_RR_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_S1000_XR_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_X1_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_X1_SAV_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_X3_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_X4_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_X5_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_X6_recalls.json to data/2016/recalls/
Moved year_2016_make_BMW_model_Z4_recalls.json to data/2016/recalls/
Moved year_2016_make_BRAUNABILITY_model_DODGE_WHEELCHAIR_VAN_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_CASCADA_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_ENCLAVE_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_ENCORE_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_ENVISION_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_LACROSSE_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_REGAL_recalls.json to data/2016/recalls/
Moved year_2016_make_BUICK_model_VERANO_recalls.json to data/2016/recalls/
Moved year_2016_make_CADILLAC_model_ATS_recalls.json to data/2016/recalls/
Moved year_2016_make_CADILLAC_model_CT6_recalls.json to data/2016/recalls/
Moved year_2016_make_CADILLAC_model_CTS_recalls.json to data/2016/recalls/
Moved year_2016_make_CADILLAC_model_ESCALADE_ESV_recalls.json to data/2016/recalls/
Moved year_2016_make_CADILLAC_model_ESCALADE_recalls.json to data/2016/recalls/
Moved year_2016_make_CADILLAC_model_SRX_recalls.json to data/2016/recalls/
Moved year_2016_make_CAN-AM_model_SPYDER_F3_recalls.json to data/2016/recalls/
Moved year_2016_make_CAN-AM_model_SPYDER_RT_recalls.json to data/2016/recalls/
Moved year_2016_make_CARGO_EXPRESS_model_CARGO_TRAILER_recalls.json to data/2016/recalls/
Moved year_2016_make_CARGO_MATE_model_ELIMINATOR_recalls.json to data/2016/recalls/
Moved year_2016_make_CEDAR_CREEK_model_SILVER_BACK_recalls.json to data/2016/recalls/
Moved year_2016_make_CHARMAC_model_CARGO_TRAILER_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEROKEE_model_GREY_WOLF_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_CAMARO_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_COLORADO_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_CORVETTE_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_CRUZE_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_EQUINOX_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_LOW_CAB_FORWARD_3500_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_MALIBU_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SILVERADO_1500_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SILVERADO_2500_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SILVERADO_3500_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SONIC_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SPARK_EV_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SPARK_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_SS_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_TAHOE_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_TRAVERSE_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_TRAX_recalls.json to data/2016/recalls/
Moved year_2016_make_CHEVROLET_model_VOLT_recalls.json to data/2016/recalls/
Moved year_2016_make_CHRYSLER_model_200_recalls.json to data/2016/recalls/
Moved year_2016_make_CHRYSLER_model_300_recalls.json to data/2016/recalls/
Moved year_2016_make_CHRYSLER_model_TOWN_AND_COUNTRY_recalls.json to data/2016/recalls/
Moved year_2016_make_COACHMEN_model_FREEDOM_EXPRESS_recalls.json to data/2016/recalls/
Moved year_2016_make_COACHMEN_model_FREELANDER_recalls.json to data/2016/recalls/
Moved year_2016_make_COACHMEN_model_GALLERIA_recalls.json to data/2016/recalls/
Moved year_2016_make_COACHMEN_model_LEPRECHAUN_recalls.json to data/2016/recalls/
Moved year_2016_make_COACHMEN_model_MIRADA_recalls.json to data/2016/recalls/
Moved year_2016_make_COACHMEN_model_ORION_recalls.json to data/2016/recalls/
Moved year_2016_make_CROSSROADS_model_SUNSET_TRAIL_recalls.json to data/2016/recalls/
Moved year_2016_make_CRUISER_RV_model_SHADOW_CRUISER_recalls.json to data/2016/recalls/
Moved year_2016_make_CRUISER_RV_model_STRYKER_TOY_recalls.json to data/2016/recalls/
Moved year_2016_make_DODGE_model_CHALLENGER_recalls.json to data/2016/recalls/
Moved year_2016_make_DODGE_model_CHARGER_recalls.json to data/2016/recalls/
Moved year_2016_make_DODGE_model_DART_recalls.json to data/2016/recalls/
Moved year_2016_make_DODGE_model_DURANGO_recalls.json to data/2016/recalls/
Moved year_2016_make_DODGE_model_GRAND_CARAVAN_recalls.json to data/2016/recalls/
Moved year_2016_make_DODGE_model_JOURNEY_recalls.json to data/2016/recalls/
Moved year_2016_make_DRV_model_ELITE_SUITES_ALL_recalls.json to data/2016/recalls/
Moved year_2016_make_DRV_model_MOBILE_SUITE_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_1299_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_MONSTER_1200_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_MULTISTRADA_1200_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_MULTISTRADA_1200S_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_MULTISTRADA_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_SCRAMBLER_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_XDIAVEL_recalls.json to data/2016/recalls/
Moved year_2016_make_DUCATI_model_XDIAVEL_S_recalls.json to data/2016/recalls/
Moved year_2016_make_DUTCHMEN_model_ASPEN_TRAIL_recalls.json to data/2016/recalls/
Moved year_2016_make_DUTCHMEN_model_DENALI_recalls.json to data/2016/recalls/
Moved year_2016_make_DYNAMAX_model_REV_recalls.json to data/2016/recalls/
Moved year_2016_make_EAST_MANUFACTURING_model_FRAME_GENESIS_TRAILER_recalls.json to data/2016/recalls/
Moved year_2016_make_ENTEGRA_model_ANTHEM_recalls.json to data/2016/recalls/
Moved year_2016_make_ENTEGRA_model_ASPIRE_recalls.json to data/2016/recalls/
Moved year_2016_make_EVERGREEN_model_BAY_HILL_recalls.json to data/2016/recalls/
\n--- Organizing data for year: 2017 ---
\n--- Organizing data for year: 2018 ---
\n--- Organizing data for year: 2019 ---
\n--- Organizing data for year: 2020 ---
\n--- Organizing data for year: 2021 ---
\n--- Organizing data for year: 2022 ---
\n--- Organizing data for year: 2023 ---
\n--- Organizing data for year: 2024 ---
\n--- Organizing data for year: 2025 ---

### Clean the Data
Put all the data into a single JSON dump named "all_recalls.json"

In [ ]:
# Don't do this if you ran all the bash scripts
%%bash
unzip dataRaw.zip

Archive:  dataRaw.zip
   creating: data/
   creating: data/2017/
   creating: data/2017/recalls/
  inflating: data/2017/recalls/year_2017_make_BMW_model_X4_recalls.json
  inflating: data/2017/recalls/year_2017_make_TRIUMPH_model_STREET_TWIN_recalls.json
  inflating: data/2017/recalls/year_2017_make_ACURA_model_NSX_recalls.json
  inflating: data/2017/recalls/year_2017_make_ACURA_model_TLX_recalls.json
  inflating: data/2017/recalls/year_2017_make_RAM_model_2500_recalls.json
  inflating: data/2017/recalls/year_2017_make_LIVIN_LITE_model_QUICKSILVER_6.0_recalls.json
  inflating: data/2017/recalls/year_2017_make_KENTUCKY_TRAILER_model_MV_recalls.json
  inflating: data/2017/recalls/year_2017_make_FREIGHTLINER_model_M2_recalls.json
  inflating: data/2017/recalls/year_2017_make_LINCOLN_model_NAVIGATOR_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_TRAVERSE_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_Q7_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_PUMA_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_EXPLORER_recalls.json
  inflating: data/2017/recalls/year_2017_make_LINCOLN_model_MKX_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_ROGUE_SPORT_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLHTKL_recalls.json
  inflating: data/2017/recalls/year_2017_make_SHASTA_model_REVERE_recalls.json
  inflating: data/2017/recalls/year_2017_make_INTERNATIONAL_model_LONESTAR_recalls.json
  inflating: data/2017/recalls/year_2017_make_RAM_model_5500_recalls.json
  inflating: data/2017/recalls/year_2017_make_CADILLAC_model_ESCALADE_ESV_recalls.json
  inflating: data/2017/recalls/year_2017_make_VANLEIGH_model_VILANO_recalls.json
  inflating: data/2017/recalls/year_2017_make_WINNEBAGO_model_FUSE_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_FORTE_recalls.json
  inflating: data/2017/recalls/year_2017_make_LEXUS_model_RX350_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_S1000_R_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_SEISMIC_WAVE_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_TAURUS_recalls.json
  inflating: data/2017/recalls/year_2017_make_LOTUS_model_EVORA_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_F-550_SD_recalls.json
  inflating: data/2017/recalls/year_2017_make_SUBARU_model_IMPREZA_recalls.json
  inflating: data/2017/recalls/year_2017_make_RAM_model_3500_recalls.json
  inflating: data/2017/recalls/year_2017_make_CADILLAC_model_ATS_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLTRXS_recalls.json
  inflating: data/2017/recalls/year_2017_make_TRIUMPH_model_STREET_CUP_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_TRAX_recalls.json
  inflating: data/2017/recalls/year_2017_make_GMC_model_SIERRA_3500_recalls.json
  inflating: data/2017/recalls/year_2017_make_KENWORTH_model_T880_recalls.json
  inflating: data/2017/recalls/year_2017_make_CAN-AM_model_SPYDER_F3_recalls.json
  inflating: data/2017/recalls/year_2017_make_PETERBILT_model_587_recalls.json
  inflating: data/2017/recalls/year_2017_make_COACHMEN_model_CROSS_COUNTRY_recalls.json
  inflating: data/2017/recalls/year_2017_make_INFINITI_model_QX30_recalls.json
  inflating: data/2017/recalls/year_2017_make_THOR_MOTOR_COACH_model_TUSCANY_XTE_recalls.json
  inflating: data/2017/recalls/year_2017_make_GENESIS_model_G90_recalls.json
  inflating: data/2017/recalls/year_2017_make_VOLVO_model_XC60_recalls.json
  inflating: data/2017/recalls/year_2017_make_SUZUKI_model_GSX-R1000_recalls.json
  inflating: data/2017/recalls/year_2017_make_PORSCHE_model_MACAN_recalls.json
  inflating: data/2017/recalls/year_2017_make_LEXUS_model_RC_F_recalls.json
  inflating: data/2017/recalls/year_2017_make_KTM_model_690_DUKE_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_RAINIER_recalls.json
  inflating: data/2017/recalls/year_2017_make_MINI_model_CLUBMAN_recalls.json
  inflating: data/2017/recalls/year_2017_make_WINNEBAGO_model_MINNIE_WINNIE_recalls.json
  inflating: data/2017/recalls/year_2017_make_MERCEDES-BENZ_model_SPRINTER_3500_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_SEDONA_recalls.json
  inflating: data/2017/recalls/year_2017_make_FERRARI_model_GTC4LUSSO_recalls.json
  inflating: data/2017/recalls/year_2017_make_ITASCA_model_SUNSTAR_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_ALANTE_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_JAY_FEATHER_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_CORVETTE_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHRYSLER_model_200_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_JAY_FLIGHT_BUNGALOW_recalls.json
  inflating: data/2017/recalls/year_2017_make_HYUNDAI_model_TUCSON_recalls.json
  inflating: data/2017/recalls/year_2017_make_PORSCHE_model_PANAMERA_recalls.json
  inflating: data/2017/recalls/year_2017_make_KEYSTONE_model_SPRINTER_recalls.json
  inflating: data/2017/recalls/year_2017_make_KEYSTONE_model_RAPTOR_recalls.json
  inflating: data/2017/recalls/year_2017_make_RAM_model_1500_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_MAXIMA_recalls.json
  inflating: data/2017/recalls/year_2017_make_LINCOLN_model_CONTINENTAL_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_REDHAWK_recalls.json
  inflating: data/2017/recalls/year_2017_make_MITSUBISHI_model_OUTLANDER_recalls.json
  inflating: data/2017/recalls/year_2017_make_DRV_model_MOBILE_SUITE_ESTATES_recalls.json
  inflating: data/2017/recalls/year_2017_make_HIGHLAND_RIDGE_model_OPEN_RANGE_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_SUNSEEKER_recalls.json
  inflating: data/2017/recalls/year_2017_make_UTILITY_TRAILER_model_VS2DC_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_PRIME_TIME_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_SANDSTORM_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_M6_recalls.json
  inflating: data/2017/recalls/year_2017_make_FREIGHTLINER_model_CORONADO_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_POLICE_INTERCEPTOR_UTILIT_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLHXSE_recalls.json
  inflating: data/2017/recalls/year_2017_make_VOLVO_model_V60_recalls.json
  inflating: data/2017/recalls/year_2017_make_TIFFIN_model_ALLEGRO_BUS_recalls.json
  inflating: data/2017/recalls/year_2017_make_TOYOTA_model_SIENNA_recalls.json
  inflating: data/2017/recalls/year_2017_make_HONDA_model_ACCORD_HYBRID_recalls.json
  inflating: data/2017/recalls/year_2017_make_CRUISER_RV_model_SOUTH_FORK_recalls.json
  inflating: data/2017/recalls/year_2017_make_INFINITI_model_QX60_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_Q5_recalls.json
  inflating: data/2017/recalls/year_2017_make_HONDA_model_RIDGELINE_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_NORTHPOINT_recalls.json
  inflating: data/2017/recalls/year_2017_make_HYUNDAI_model_SANTA_FE_SPORT_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_X5_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_SIERRA_recalls.json
  inflating: data/2017/recalls/year_2017_make_WESTERN_STAR_model_4700_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLHTK_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_PINNACLE_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_WILDWOOD_recalls.json
  inflating: data/2017/recalls/year_2017_make_DODGE_model_CHALLENGER_recalls.json
  inflating: data/2017/recalls/year_2017_make_KEYSTONE_model_RESIDENCE_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_SANDPIPER_recalls.json
  inflating: data/2017/recalls/year_2017_make_DRV_model_ELITE_SUITE_recalls.json
  inflating: data/2017/recalls/year_2017_make_PIERCE_model_SABER_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_NV3500_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_XLR_TOYHAULER_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_R1200_GS_ADVENTURE_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_A3_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_MURANO_recalls.json
  inflating: data/2017/recalls/year_2017_make_PORSCHE_model_PANAMERA_TURBO_EXECUTIVE_recalls.json
  inflating: data/2017/recalls/year_2017_make_TRIUMPH_model_THRUXTON_recalls.json
  inflating: data/2017/recalls/year_2017_make_NEWMAR_model_BAY_STAR_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_TAHOE_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_F-550_recalls.json
  inflating: data/2017/recalls/year_2017_make_URAL_model_GEAR-UP_recalls.json
  inflating: data/2017/recalls/year_2017_make_GMC_model_CANYON_recalls.json
  inflating: data/2017/recalls/year_2017_make_VOLKSWAGEN_model_PASSAT_recalls.json
  inflating: data/2017/recalls/year_2017_make_KEYSTONE_model_OUTBACK_recalls.json
  inflating: data/2017/recalls/year_2017_make_HYUNDAI_model_IONIQ_ELECTRIC_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLHXS_recalls.json
  inflating: data/2017/recalls/year_2017_make_ACURA_model_RDX_recalls.json
  inflating: data/2017/recalls/year_2017_make_PORSCHE_model_PANAMERA_4_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_WOLF_PACK_recalls.json
  inflating: data/2017/recalls/year_2017_make_PORSCHE_model_MACAN_GTS_recalls.json
  inflating: data/2017/recalls/year_2017_make_SUBARU_model_CROSSTREK_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_STEALTH_recalls.json
  inflating: data/2017/recalls/year_2017_make_COACHMEN_model_FREEDOM_EXPRESS_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_S6_recalls.json
  inflating: data/2017/recalls/year_2017_make_FREIGHTLINER_model_SPRINTER_3500_recalls.json
  inflating: data/2017/recalls/year_2017_make_COACHMEN_model_PRISM_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_FLEX_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHRYSLER_model_TOWN_AND_COUNTRY_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_SALEM_recalls.json
  inflating: data/2017/recalls/year_2017_make_TRIUMPH_model_BONNEVILLE_T100_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_SENTRA_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_EXPEDITION_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_X3_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLSTFBS_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_ROCKWOOD_recalls.json
  inflating: data/2017/recalls/year_2017_make_TOYOTA_model_PRIUS_C_recalls.json
  inflating: data/2017/recalls/year_2017_make_MASERATI_model_QUATTROPORTE_recalls.json
  inflating: data/2017/recalls/year_2017_make_HONDA_model_CRF1000A_recalls.json
  inflating: data/2017/recalls/year_2017_make_BUICK_model_VERANO_recalls.json
  inflating: data/2017/recalls/year_2017_make_WINNEBAGO_model_MINNIE_recalls.json
  inflating: data/2017/recalls/year_2017_make_COACHMEN_model_GALLERIA_recalls.json
  inflating: data/2017/recalls/year_2017_make_WINNEBAGO_model_TOUR_recalls.json
  inflating: data/2017/recalls/year_2017_make_FREIGHTLINER_model_BUSINESS_CLASS_M2_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_COLORADO_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_OPTIMA_recalls.json
  inflating: data/2017/recalls/year_2017_make_POLARIS_model_SLINGSHOT_recalls.json
  inflating: data/2017/recalls/year_2017_make_GRAND_DESIGN_model_REFLECTION_recalls.json
  inflating: data/2017/recalls/year_2017_make_MAZDA_model_MAZDA3_recalls.json
  inflating: data/2017/recalls/year_2017_make_INDIAN_model_CHIEF_recalls.json
  inflating: data/2017/recalls/year_2017_make_FLEETWOOD_model_PACE_ARROW_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_E-450_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_SPORTAGE_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_SORENTO_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_F-450_recalls.json
  inflating: data/2017/recalls/year_2017_make_FLEETWOOD_model_DISCOVERY_recalls.json
  inflating: data/2017/recalls/year_2017_make_MCI_model_D4505_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_RIVERSTONE_LEGACY_recalls.json
  inflating: data/2017/recalls/year_2017_make_AIRSTREAM_model_BASECAMP_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_CAMARO_recalls.json
  inflating: data/2017/recalls/year_2017_make_DYNAMAX_model_REV_recalls.json
  inflating: data/2017/recalls/year_2017_make_STARCRAFT_model_AUTUMN_RIDGE_recalls.json
  inflating: data/2017/recalls/year_2017_make_DRV_model_MOBILE_SUITE_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_ALLROAD_recalls.json
  inflating: data/2017/recalls/year_2017_make_VAN_HOOL_model_CX35_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_OPTIMA_HYBRID_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_GREYHAWK_recalls.json
  inflating: data/2017/recalls/year_2017_make_TOYOTA_model_PRIUS_recalls.json
  inflating: data/2017/recalls/year_2017_make_KENWORTH_model_T680_recalls.json
  inflating: data/2017/recalls/year_2017_make_GMC_model_SIERRA_1500_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_RIO_recalls.json
  inflating: data/2017/recalls/year_2017_make_GMC_model_SIERRA_2500_recalls.json
  inflating: data/2017/recalls/year_2017_make_HYUNDAI_model_SANTA_FE_recalls.json
  inflating: data/2017/recalls/year_2017_make_PACE_model_CARGO_TRAILER_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FXSE_recalls.json
  inflating: data/2017/recalls/year_2017_make_TRIUMPH_model_THRUXTON_R_recalls.json
  inflating: data/2017/recalls/year_2017_make_CHEVROLET_model_SPARK_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_NV_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_FRONTIER_recalls.json
  inflating: data/2017/recalls/year_2017_make_KEYSTONE_model_ALPINE_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_NV2500_recalls.json
  inflating: data/2017/recalls/year_2017_make_KTM_model_1290_SUPER_DUKE_GT_recalls.json
  inflating: data/2017/recalls/year_2017_make_CROSSROADS_model_SUNSET_TRAIL_recalls.json
  inflating: data/2017/recalls/year_2017_make_HAUL_MASTER_model_UTILITY_TRAILER_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_SENECA_recalls.json
  inflating: data/2017/recalls/year_2017_make_HIGHLAND_RIDGE_model_MESA_RIDGE_recalls.json
  inflating: data/2017/recalls/year_2017_make_THOR_model_PALAZZO_recalls.json
  inflating: data/2017/recalls/year_2017_make_GMC_model_ACADIA_recalls.json
  inflating: data/2017/recalls/year_2017_make_BUICK_model_ENVISION_recalls.json
  inflating: data/2017/recalls/year_2017_make_VOLKSWAGEN_model_JETTA_recalls.json
  inflating: data/2017/recalls/year_2017_make_CADILLAC_model_CT6_recalls.json
  inflating: data/2017/recalls/year_2017_make_HONDA_model_PILOT_recalls.json
  inflating: data/2017/recalls/year_2017_make_VOLKSWAGEN_model_BEETLE_recalls.json
  inflating: data/2017/recalls/year_2017_make_ENTEGRA_model_INSIGNIA_recalls.json
  inflating: data/2017/recalls/year_2017_make_LINCOLN_model_MKZ_recalls.json
  inflating: data/2017/recalls/year_2017_make_MAZDA_model_MAZDA6_recalls.json
  inflating: data/2017/recalls/year_2017_make_COACHMEN_model_LEPRECHAUN_recalls.json
  inflating: data/2017/recalls/year_2017_make_DODGE_model_CHARGER_recalls.json
  inflating: data/2017/recalls/year_2017_make_SUBARU_model_FORESTER_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_CHEROKEE_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_S3_recalls.json
  inflating: data/2017/recalls/year_2017_make_DUTCHMEN_model_VOLTAGE_recalls.json
  inflating: data/2017/recalls/year_2017_make_NISSAN_model_ROGUE_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLRT_recalls.json
  inflating: data/2017/recalls/year_2017_make_TOYOTA_model_CAMRY_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_ECONOLINE_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_540I_recalls.json
  inflating: data/2017/recalls/year_2017_make_DODGE_model_JOURNEY_recalls.json
  inflating: data/2017/recalls/year_2017_make_MAZDA_model_MX-5_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_XG750_recalls.json
  inflating: data/2017/recalls/year_2017_make_FERRARI_model_488_GTB_recalls.json
  inflating: data/2017/recalls/year_2017_make_CADILLAC_model_ESCALADE_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_A7_recalls.json
  inflating: data/2017/recalls/year_2017_make_VICTORY_model_MAGNUM_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_A5_recalls.json
  inflating: data/2017/recalls/year_2017_make_FORD_model_TRANSIT_recalls.json
  inflating: data/2017/recalls/year_2017_make_ACURA_model_MDX_SPORT_HYBRID_recalls.json
  inflating: data/2017/recalls/year_2017_make_KIA_model_CADENZA_recalls.json
  inflating: data/2017/recalls/year_2017_make_ISUZU_model_NPR_recalls.json
  inflating: data/2017/recalls/year_2017_make_TESLA_model_MODEL_3_recalls.json
  inflating: data/2017/recalls/year_2017_make_TOYOTA_model_RAV4_recalls.json
  inflating: data/2017/recalls/year_2017_make_SUBARU_model_OUTBACK_recalls.json
  inflating: data/2017/recalls/year_2017_make_FOREST_RIVER_model_SPARTAN_recalls.json
  inflating: data/2017/recalls/year_2017_make_DUCATI_model_MONSTER_797_recalls.json
  inflating: data/2017/recalls/year_2017_make_MASERATI_model_GHIBLI_recalls.json
  inflating: data/2017/recalls/year_2017_make_BUICK_model_ENCORE_recalls.json
  inflating: data/2017/recalls/year_2017_make_HONDA_model_ACCORD_recalls.json
  inflating: data/2017/recalls/year_2017_make_INDIAN_model_CHIEF_VINTAGE_recalls.json
  inflating: data/2017/recalls/year_2017_make_TRIUMPH_model_SPEED_TRIPLE_R_recalls.json
  inflating: data/2017/recalls/year_2017_make_JAYCO_model_JAY_FLIGHT_recalls.json
  inflating: data/2017/recalls/year_2017_make_TOYOTA_model_TACOMA_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_FLHX_recalls.json
  inflating: data/2017/recalls/year_2017_make_HARLEY-DAVIDSON_model_XG750A_recalls.json
  inflating: data/2017/recalls/year_2017_make_MINI_model_COOPER_recalls.json
  inflating: data/2017/recalls/year_2017_make_LINCOLN_model_MKT_recalls.json
  inflating: data/2017/recalls/year_2017_make_SUBARU_model_LEGACY_recalls.json
  inflating: data/2017/recalls/year_2017_make_WINNEBAGO_model_ERA_recalls.json
  inflating: data/2017/recalls/year_2017_make_FIAT_model_500X_recalls.json
  inflating: data/2017/recalls/year_2017_make_KZRV_model_VENOM_recalls.json
  inflating: data/2017/recalls/year_2017_make_HYUNDAI_model_SONATA_recalls.json
  inflating: data/2017/recalls/year_2017_make_BMW_model_R1200_GS_recalls.json
  inflating: data/2017/recalls/year_2017_make_VOLKSWAGEN_model_CC_recalls.json
  inflating: data/2017/recalls/year_2017_make_ITASCA_model_SPIRIT_recalls.json
  inflating: data/2017/recalls/year_2017_make_AUDI_model_A4_recalls.json
  inflating: data/2017/recalls/year_2017_make_KEYSTONE_model_BULLET_recalls.json

In [ ]:
import json
import re
import glob
# glob is used to find pathnames matching a specific pattern
recall_files = glob.glob("data/**/recalls/*.json", recursive=True)

# List to store all extracted recall information
all_recalls_data = []
for filenames in recall_files:
  with open(str(filenames)) as f:
    data = json.load(f)
    result = data['results']
    resultSet = []
    #print(json.dumps(result, indent=2))
    for indent in result:
      # Extract only the part of the component string before the first ':', ',', ' ' or ';'
      component_full = indent['Component']
      match = re.search(r'([^:,;]+)', component_full)
      comp = match.group(1) if match else component_full

      mYear = indent['ModelYear']
      make = indent['Make']
      model = indent['Model']
      resultSet.append({
          'Component': comp,
          'ModelYear': mYear,
          'Make': make,
          'Model': model
      })
    # Changed 'all' to 'all_recalls_data.extend(resultSet)' to actually store the results
    all_recalls_data.extend(resultSet)
    #print(json.dumps(resultSet, indent=2))

output_file_name = 'all_recalls.json'

with open(output_file_name, 'w') as f:
    json.dump(all_recalls_data, f, indent=4)

print(f"All recalls data saved to {output_file_name}")

All recalls data saved to all_recalls.json

## Load JSON Data
Save the file as a variable

In [1]:
import json

output_file_name = 'all_recalls.json'

with open(output_file_name, 'r') as f:
    recall_data = json.load(f)

print(f"Successfully loaded {len(recall_data)} recall entries from {output_file_name}.")

Successfully loaded 14761 recall entries from all_recalls.json.

###Initialize SQLite Connection

In [2]:
import sqlite3

db_name = 'recalls.db'
conn = sqlite3.connect(db_name)
cursor = conn.cursor()
print(f"Connected to SQLite database: {db_name}")

Connected to SQLite database: recalls.db

###Initialize Recalls and Makes Tables

In [3]:
cursor.execute('''
CREATE TABLE IF NOT EXISTS makes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);
''')

cursor.execute('''
CREATE TABLE IF NOT EXISTS recalls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    year TEXT NOT NULL,
    make_id INTEGER NOT NULL,
    model TEXT NOT NULL,
    component TEXT NOT NULL,
    FOREIGN KEY (make_id) REFERENCES makes(id)
);
''')

conn.commit()

##Fill The Tables

Parses through the all_recalls JSON file

Every unique make (manufacturer) gets assigned an Id and put into the makes table

The rest of the json data is put into the recalls table

In [4]:
for entry in recall_data:
    make_name = entry['Make']
    model_year = entry['ModelYear']
    model_name = entry['Model']
    component = entry['Component']

    # Insert unique make into the 'makes' table
    cursor.execute('INSERT OR IGNORE INTO makes (name) VALUES (?)', (make_name,))
    conn.commit()

    # Get the make_id for the inserted or existing make
    cursor.execute('SELECT id FROM makes WHERE name = ?', (make_name,))
    make_id = cursor.fetchone()[0]

    # Insert recall data into the 'recalls' table
    cursor.execute(
        'INSERT INTO recalls (year, make_id, model, component) VALUES (?, ?, ?, ?)',
        (model_year, make_id, model_name, component)
    )

conn.commit()

prints the the first 5 raw rows of each table

In [ ]:

db_name = 'recalls.db'
conn = sqlite3.connect(db_name)
cursor = conn.cursor()

print("\n--- First 5 rows from 'makes' table ---")
cursor.execute('SELECT * FROM makes LIMIT 5')
makes_rows = cursor.fetchall()
for row in makes_rows:
    print(row)

print("\n--- First 5 rows from 'recalls' table ---")
cursor.execute('SELECT * FROM recalls LIMIT 5')
recalls_rows = cursor.fetchall()
for row in recalls_rows:
    print(row)

conn.close()

--- First 5 rows from 'makes' table ---
(1, 'AUDI')
(4, 'FORD')
(7, 'VOLKSWAGEN')
(16, 'FOREST RIVER')
(23, 'PORSCHE')

--- First 5 rows from 'recalls' table ---
(1, '2016', 1, 'A4', 'ENGINE AND ENGINE COOLING')
(2, '2016', 1, 'A4', 'ELECTRICAL SYSTEM')
(3, '2016', 1, 'A4', 'ENGINE AND ENGINE COOLING')
(4, '2016', 4, 'E-350', 'SEATS')
(5, '2016', 4, 'E-350', 'ELECTRICAL SYSTEM')

###Basic Pandas Dataframes

In [5]:
import pandas as pd
con = sqlite3.connect("recalls.db")
query_recalls = "SELECT * FROM recalls;"
query_makes = "SELECT * FROM makes"
recalls_df = pd.read_sql_query(query_recalls, con)
makes_df = pd.read_sql_query(query_makes, con)

In [6]:
recalls_df.to_csv('recalls_df.csv', index=False)
print("recalls_df saved to recalls_df.csv")

recalls_df saved to recalls_df.csv

In [7]:
makes_df.to_csv('makes_df.csv', index=False)
print("makes_df saved to makes_df.csv")

makes_df saved to makes_df.csv

In [ ]:
makes_df.head()

   id          name
0   1          AUDI
1   4          FORD
2   7    VOLKSWAGEN
3  16  FOREST RIVER
4  23       PORSCHE

###Most Common Manufacturers

This query gets the most common manufacturers that have recalls for their models in the last 10 years

In [ ]:
recalls_var = 'recalls.db'
conn = sqlite3.connect(recalls_var)

# SQL query to count components for each make_id
query_component_counts = """
SELECT
    m.name AS make_name,
    COUNT(r.component) AS component_count
FROM
    makes AS m
JOIN
    recalls AS r ON m.id = r.make_id
GROUP BY
    m.name
ORDER BY
    component_count DESC
"""

# Load the results into a pandas DataFrame
component_counts_df = pd.read_sql_query(query_component_counts, conn)

# Display the first 5 rows of the new DataFrame
display(component_counts_df.head(10))

conn.close()

      make_name  component_count
0          FORD             1110
1  FOREST RIVER              662
2        TOYOTA              568
3           BMW              560
4     CHEVROLET              473
5         HONDA              443
6           RAM              433
7          AUDI              430
8        NEWMAR              408
9    VOLKSWAGEN              371

### Major Trends
Question: What are the major trends in vehicle safety recalls in the United States?
<br><br>
Purpose: To show the most common recall type of all vehicals in the United States

In [ ]:
db_name = 'recalls.db'
conn = sqlite3.connect(db_name)

# SQL query to count all components and order by count DESC
query_all_component_counts = """
SELECT
    r.component,
    COUNT(r.component) AS component_count
FROM
    recalls AS r
GROUP BY
    r.component
ORDER BY
    component_count DESC
"""

# Load the results into a pandas DataFrame
all_component_counts_df = pd.read_sql_query(query_all_component_counts, conn)

display(all_component_counts_df.head(10))

conn.close()

              component  component_count
0             EQUIPMENT             2219
1     ELECTRICAL SYSTEM             1921
2        SERVICE BRAKES             1078
3           FUEL SYSTEM             1066
4              AIR BAGS              905
5           POWER TRAIN              874
6  BACK OVER PREVENTION              808
7             STRUCTURE              715
8     EXTERIOR LIGHTING              688
9              STEERING              640

###FORD Manufacure Results

This query takes the most common manufacturer (FORD) and makes a component count data frame.

This counts FORD vehical components from the last 10 years that get recalled and shows the most common component that is recalled.

In [ ]:
db_name = 'recalls.db'
conn = sqlite3.connect(db_name)

# SQL query to count components for 'FORD' and order by count DESC
query_ford_component_counts = """
SELECT
    r.component,
    COUNT(r.component) AS component_count
FROM
    makes AS m
JOIN
    recalls AS r ON m.id = r.make_id
WHERE
    m.name = 'FORD'
GROUP BY
    r.component
ORDER BY
    component_count DESC
"""

# Load the results into a pandas DataFrame
ford_component_counts_df = pd.read_sql_query(query_ford_component_counts, conn)

display(ford_component_counts_df)

conn.close()

                      component  component_count
0          BACK OVER PREVENTION              183
1                   POWER TRAIN              147
2                   FUEL SYSTEM              100
3                     EQUIPMENT               97
4             ELECTRICAL SYSTEM               79
5                         SEATS               65
6                    VISIBILITY               47
7             EXTERIOR LIGHTING               44
8                      STEERING               41
9                SERVICE BRAKES               41
10                    STRUCTURE               40
11    ENGINE AND ENGINE COOLING               38
12                       ENGINE               35
13                   SUSPENSION               33
14                   SEAT BELTS               32
15                     AIR BAGS               28
16       LATCHES/LOCKS/LINKAGES               22
17                        TIRES                9
18                PARKING BRAKE                7
19  FORWARD COLLISION AVOIDANCE                5
20  EQUIPMENT ADAPTIVE/MOBILITY                5
21                       WHEELS                4
22              TRAILER HITCHES                4
23     HYBRID PROPULSION SYSTEM                2
24                   CHILD SEAT                2

from matplotlib import pyplot as plt
ford_component_counts_df['component_count'].plot(kind='hist', bins=20, title='component_count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ford_component_counts_df['component_count'].plot(kind='line', figsize=(8, 4), title='component_count')
plt.gca().spines[['top', 'right']].set_visible(False)

###CHEVROLET Manufacture Recalls

In [ ]:
db_name = 'recalls.db'
conn = sqlite3.connect(db_name)

# SQL query to count components for 'FORD' and order by count DESC
query_ford_component_counts = """
SELECT
    r.component,
    COUNT(r.component) AS component_count
FROM
    makes AS m
JOIN
    recalls AS r ON m.id = r.make_id
WHERE
    m.name = 'CHEVROLET'
GROUP BY
    r.component
ORDER BY
    component_count DESC
"""

# Load the results into a pandas DataFrame
ford_component_counts_df = pd.read_sql_query(query_ford_component_counts, conn)

display(ford_component_counts_df)

conn.close()

                             component  component_count
0                             AIR BAGS               85
1                       SERVICE BRAKES               60
2                           SEAT BELTS               56
3                          POWER TRAIN               41
4                          FUEL SYSTEM               39
5                    ELECTRICAL SYSTEM               33
6               LATCHES/LOCKS/LINKAGES               21
7                                TIRES               20
8                            STRUCTURE               18
9                                SEATS               14
10                           EQUIPMENT               14
11                          SUSPENSION               13
12                            STEERING               13
13                   EXTERIOR LIGHTING               12
14           ENGINE AND ENGINE COOLING               12
15                              ENGINE                6
16                          CHILD SEAT                5
17                              WHEELS                2
18                          VISIBILITY                2
19                       PARKING BRAKE                2
20         FORWARD COLLISION AVOIDANCE                2
21               VEHICLE SPEED CONTROL                1
22                     TRAILER HITCHES                1
23  ELECTRONIC STABILITY CONTROL (ESC)                1